version: "3"
services:

  # TODO: migrate data: logs / libs / pdfs (blog)
  # postfix/dovecot:
  # - https://github.com/tomav/docker-mailserver
  # - https://github.com/hardware/mailserver

  # certbot:
  #   image: certbot/certbot
  #   restart: "no"
  #   volumes:
  #     - /etc/letsencrypt:/etc/letsencrypt
  #     - ./var/letsencrypt:/var/lib/letsencrypt
  #     - ./var/acme:/var/www/acme
  #   command: certbot renew --renew-hook 'touch /var/www/.updated'
  #   cap_drop:
  #     - all

  nginx:
    build: modules/nginx
    restart: always
    volumes:
      - ./etc/nginx:/etc/nginx/
      - /etc/letsencrypt:/etc/letsencrypt
      - ./var/acme:/var/www/acme
      - ./var/blog:/var/www/blog
      - ./var/nginx:/var/log/nginx
    ports:
      - "443:443"
      - "80:80"
      - "6543:6543"
    cap_drop:
      - all
    cap_add:
      - chown
      - dac_override
      - net_bind_service
      - setgid
      - setuid

  blog:
    build: modules/blog
    restart: "no"           # build + exit
    volumes:
      - ./modules/blog:/blog
      - ./var/blog:/blog/_build
    command: ./blogdown build
    cap_drop:
      - all

  sudoku:
    build: modules/sudoku
    restart: always
#   ports:
#     - "3000:3000"
    cap_drop:
      - all

#   pycbox:
#     build: modules/pycbox
#     restart: always
# #   ports:
# #     - "5000:5000"
#     volumes:
#       - ./modules/pycbox/pycbox:/pycbox/pycbox
#       - ./var/pycbox/files:/pycbox/files
#       - ./var/pycbox/cache:/pycbox/cache
#       - ./var/pycbox/hilite:/pycbox/hilite
#     cap_drop:
#       - all
#     cap_add:
#       - chown
#       - setgid
#       - setuid

  gogs:
    image: gogs/gogs
    restart: always
    volumes:
      - "./var/gogs:/data"
    ports:
      - "22:22"
#     - "3000:3000"
    cap_drop:
      - all
    cap_add:
      - chown
      - dac_override
      - fowner
      - net_bind_service
      - setgid
      - setuid

  murmur:
    build: modules/murmur
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./etc/murmur:/etc/murmur
      - ./var/murmur/log:/var/log/murmur
      - ./var/murmur/lib:/var/lib/murmur
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
   #cap_drop:
   #  - all
   #cap_add:
   #  - chown
   #  - dac_override
   #  - setgid
   #  - setuid

  ejabberd:
    build: modules/ejabberd
    restart: always
    volumes:
      - ./etc/ejabberd:/home/ejabberd/conf
      - ./var/ejabberd/database:/home/ejabberd/database
      - ./var/ejabberd/logs:/home/ejabberd/logs
      - ./var/ejabberd/ssl:/home/ejabberd/ssl
      - ./var/ejabberd/upload:/home/ejabberd/upload
    ports:
      - "1883:1883"     # mod_mqtt
      - "5222:5222"     # ejabberd_c2s
      - "5269:5269"     # ejabberd_s2s_in
    # tunneled through nginx:
    # - "5280:5280"     # ejabberd_http/http
    # - "5443:5443"     # ejabberd_http/https
    environment:
      - TZ=Europe/Berlin
    cap_drop:
      - all

  # tty-proxy
  tty-proxy:
    build: modules/tty-proxy
    restart: always
    # ports:
    # - "6543:3456"
    # - "8080:8080"
    environment:
      URL: https://tty.coldfix.de
    cap_drop:
      - all

  # dyndns:
  ddns:
    restart: always
    build:
      context: modules/ddns
      dockerfile: docker/ddns/Dockerfile
    depends_on:
      - ddns_redis
#   ports:
#     - "8082:8080"
    environment:
      DDNS_DOMAIN:     dns.coldfix.de
      DDNS_SOA_DOMAIN: ddns.coldfix.de
      DDNS_REDIS_HOST: ddns_redis:6379
      DDNS_EXPIRATION_DAYS: 180

  ddns_powerdns:
    build: modules/ddns/docker/powerdns
    restart: always
    depends_on:
      - ddns
    ports:
      - "53:53/udp"
    environment:
      PDNS_REMOTE_HTTP_HOST: ddns:8053

  ddns_redis:
    restart: always
    image: redis:4-alpine
    volumes:
      - "./var/ddns:/data"

  minecraft:
    restart: always
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      ENABLE_AUTOPAUSE: "TRUE"
      AUTOPAUSE_TIMEOUT_EST: 300
      AUTOPAUSE_TIMEOUT_INIT: 300
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: "-1"
      TZ: Europe/Berlin
    volumes:
      - "./var/minecraft:/data"
