version: "3"
services:

  # TODO: migrate data: pypi / logs / libs / pdfs (blog)
  # postfix/dovecot:
  # - https://github.com/tomav/docker-mailserver
  # - https://github.com/hardware/mailserver

  web:
    build: modules/nginx
    restart: always
    volumes:
      - ./etc/nginx:/etc/nginx/
      - /etc/letsencrypt:/etc/letsencrypt
      - ./var/blog:/var/www/blog
      - ./var/pypi:/var/www/pypi
      - ./var/nginx:/var/log/nginx
    ports:
      - "443:443"
      - "80:80"

  blog:
    build: modules/blog
    restart: "no"           # build + exit
    volumes:
      - ./modules/blog:/blog
      - ./var/blog:/blog/_build
    command: run-blogdown build

  goaccess:
    build: modules/goaccess
    restart: always
    volumes:
      - ./etc/goaccess:/srv/data
      - ./var/goaccess:/srv/report
      - ./var/nginx:/srv/logs
    ports:
      - "7890:7890"

  sudoku:
    build: modules/sudoku
    restart: always
#   ports:
#     - "3000:3000"

  picbox:
    build: modules/picbox
    restart: always
#   ports:
#     - "80:80"
    volumes:
      - ./modules/picbox:/picbox
      - ./var/picbox:/picbox/files
    environment:
      - HTTP_AUTH=none

  gogs:
    image: gogs/gogs
    restart: always
    volumes:
      - "./var/gogs:/data"
    ports:
      - "22:22"
#     - "3000:3000"

  kansha:
    image: netng/kansha
    restart: always
#   ports:
#     - "8080:8080"

  cryptpad:
    build: modules/cryptpad
    restart: always
    volumes:
      - ./etc/cryptpad:/cryptpad/customize
      - ./var/cryptpad:/cryptpad/datastore
#   ports:
#     - "3000:3000"     # TODO: needed for websockets?

  pins:
    build: modules/pins
    restart: always
    volumes:
      - ./var/pins:/tmp/shields.py
#   ports:
#     - "8080:8080"

  redis:
    image: redis:alpine
    restart: always

  murmur:
    build: modules/murmur
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./etc/murmur:/etc/murmur
      - ./var/murmur/log:/var/log/murmur
      - ./var/murmur/lib:/var/lib/murmur
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"

  ejabberd:
    image: rroemhild/ejabberd
    restart: always
    volumes:
      - ./etc/ejabberd:/opt/ejabberd/conf
      - ./var/ejabberd:/opt/ejabberd/database
      - ./var/ssl:/opt/ejabberd/ssl
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
    environment:
      - XMPP_DOMAIN=coldfix.de coldfix.eu fireflake.de fireflake.eu
      - TZ=Europe/Berlin
      - EJABBERD_SKIP_MAKE_SSLCERT=1
    hostname: coldfix.de
    domainname: coldfix.de
