version: "3"
services:

  # TODO: migrate data: pypi / logs / libs / pdfs (blog)
  # postfix/dovecot:
  # - https://github.com/tomav/docker-mailserver
  # - https://github.com/hardware/mailserver

  # certbot:
  #   image: certbot/certbot
  #   restart: "no"
  #   volumes:
  #     - /etc/letsencrypt:/etc/letsencrypt
  #     - ./var/letsencrypt:/var/lib/letsencrypt
  #     - ./var/acme:/var/www/acme
  #   command: certbot renew --renew-hook 'touch /var/www/.updated'
  #   cap_drop:
  #     - all

  nginx:
    build: modules/nginx
    restart: always
    volumes:
      - ./etc/nginx:/etc/nginx/
      - /etc/letsencrypt:/etc/letsencrypt
      - ./var/acme:/var/www/acme
      - ./var/blog:/var/www/blog
      - ./var/pypi:/var/www/pypi
      - ./var/nginx:/var/log/nginx
    ports:
      - "443:443"
      - "80:80"
    cap_drop:
      - all
    cap_add:
      - chown
      - dac_override
      - net_bind_service
      - setgid
      - setuid

  blog:
    build: modules/blog
    restart: "no"           # build + exit
    volumes:
      - ./modules/blog:/blog
      - ./var/blog:/blog/_build
    command: ./blogdown build
    cap_drop:
      - all

  sudoku:
    build: modules/sudoku
    restart: always
#   ports:
#     - "3000:3000"
    cap_drop:
      - all

  pycbox:
    build: modules/pycbox
    restart: always
#   ports:
#     - "5000:5000"
    volumes:
      - ./modules/pycbox/pycbox:/pycbox/pycbox
      - ./var/pycbox/files:/pycbox/files
      - ./var/pycbox/cache:/pycbox/cache
      - ./var/pycbox/hilite:/pycbox/hilite
    cap_drop:
      - all
    cap_add:
      - chown
      - setgid
      - setuid

  gogs:
    image: gogs/gogs
    restart: always
    volumes:
      - "./var/gogs:/data"
    ports:
      - "22:22"
#     - "3000:3000"
    cap_drop:
      - all
    cap_add:
      - chown
      - dac_override
      - fowner
      - net_bind_service
      - setgid
      - setuid

  kansha:
    image: netng/kansha
    restart: always
#   ports:
#     - "8080:8080"
    cap_drop:
      - all

  cryptpad:
    build: modules/cryptpad
    restart: always
    volumes:
      - ./etc/cryptpad:/cryptpad/customize
      - ./var/cryptpad:/cryptpad/datastore
    environment:
      - USE_SSL=true
      - LOG_TO_STDOUT=true
      - STORAGE='./storage/file'
#   ports:
#     - "3000:3000"
    cap_drop:
      - all

  murmur:
    build: modules/murmur
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./etc/murmur:/etc/murmur
      - ./var/murmur/log:/var/log/murmur
      - ./var/murmur/lib:/var/lib/murmur
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
   #cap_drop:
   #  - all
   #cap_add:
   #  - chown
   #  - dac_override
   #  - setgid
   #  - setuid

  ejabberd:
    image: rroemhild/ejabberd
    restart: always
    volumes:
      - ./etc/ejabberd:/opt/ejabberd/conf
      - ./var/ejabberd:/opt/ejabberd/database
      - ./var/ssl:/opt/ejabberd/ssl
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
    environment:
      - XMPP_DOMAIN=coldfix.de coldfix.eu fireflake.de fireflake.eu
      - TZ=Europe/Berlin
      - EJABBERD_SKIP_MAKE_SSLCERT=1
    hostname: coldfix.de
    domainname: coldfix.de
    cap_drop:
      - all
