version: "3"
services:

  web:
    build: modules/nginx
    volumes:
      - ./nginx/conf:/etc/nginx/
      - /etc/letsencrypt:/etc/letsencrypt
      - ./blog/_build:/var/www/blog
    ports:
      - "443:443"
      - "80:80"

  blog:
    build: modules/blog
    volumes:
      - ./blog:/blog
    command: run-blogdown build

  sudoku:
    build: modules/sudoku

  gogs:
    image: gogs/gogs
    volumes:
      - "./gogs/data:/data"

  cryptpad:
    build: modules/cryptpad
    volumes:
      - ./cryptpad/datastore:/cryptpad/datastore
      - ./cryptpad/customize:/cryptpad/customize

  pins:
    build: modules/pins

  redis:
    image: redis:alpine
