version: "3"
services:

  web:
    build: nginx
    volumes:
      - ./nginx/conf:/etc/nginx/
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "443:443"
      - "80:80"

  blog:
    build: blog
    volumes:
      - ./blog:/blog
    ports:
      - "5000:5000"

  sudoku:
    build: sudoku

  gogs:
    image: gogs/gogs
    volumes:
      - "./gogs/data:/data"
