version: "3"
services:

  # TODO: migrate data: pypi / logs / libs / pdfs (blog)
  # postfix/dovecot:
  # - https://github.com/tomav/docker-mailserver
  # - https://github.com/hardware/mailserver

  nginx:
    build: modules/nginx
    restart: always
    volumes:
      - ./etc/nginx:/etc/nginx/
      - /etc/letsencrypt:/etc/letsencrypt
      - ./var/blog:/var/www/blog
      - ./var/pypi:/var/www/pypi
      - ./var/nginx:/var/log/nginx
    ports:
      - "443:443"
      - "80:80"
    cap_drop:
      - all
    cap_add:
      - chown
      - dac_override
      - net_bind_service
      - setgid
      - setuid

  blog:
    build: modules/blog
    restart: "no"           # build + exit
    volumes:
      - ./modules/blog:/blog
      - ./var/blog:/blog/_build
    command: run-blogdown build
    cap_drop:
      - all

  goaccess:
    build: modules/goaccess
    restart: always
    volumes:
      - ./etc/goaccess:/srv/data
      - ./var/goaccess:/srv/report
      - ./var/nginx:/srv/logs
    ports:
      - "7890:7890"
    cap_drop:
      - all

  sudoku:
    build: modules/sudoku
    restart: always
#   ports:
#     - "3000:3000"
    cap_drop:
      - all

  pycbox:
    build: modules/pycbox
    restart: always
#   ports:
#     - "5000:5000"
    volumes:
      - ./modules/pycbox/pycbox.py:/pycbox/pycbox.py
      - ./var/pycbox:/pycbox/files
    cap_drop:
      - all

  gogs:
    image: gogs/gogs
    restart: always
    volumes:
      - "./var/gogs:/data"
    ports:
      - "22:22"
#     - "3000:3000"
    cap_drop:
      - all
    cap_add:
      - chown
      - dac_override
      - fowner
      - net_bind_service
      - setgid
      - setuid

  kansha:
    image: netng/kansha
    restart: always
#   ports:
#     - "8080:8080"
    cap_drop:
      - all

  cryptpad:
    build: modules/cryptpad
    restart: always
    volumes:
      - ./etc/cryptpad:/cryptpad/customize
      - ./var/cryptpad:/cryptpad/datastore
#   ports:
#     - "3000:3000"     # TODO: needed for websockets?
    cap_drop:
      - all

  pins:
    build: modules/pins
    restart: always
    volumes:
      - ./var/pins:/tmp/shields.py
#   ports:
#     - "8080:8080"
    cap_drop:
      - all

  redis:
    image: redis:alpine
    restart: always
    cap_drop:
      - all
    cap_add:
      - chown
      - setgid
      - setuid

  murmur:
    build: modules/murmur
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./etc/murmur:/etc/murmur
      - ./var/murmur/log:/var/log/murmur
      - ./var/murmur/lib:/var/lib/murmur
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
    cap_drop:
      - all
    cap_add:
      - chown
      - dac_override
      - setgid
      - setuid

  ejabberd:
    image: rroemhild/ejabberd
    restart: always
    volumes:
      - ./etc/ejabberd:/opt/ejabberd/conf
      - ./var/ejabberd:/opt/ejabberd/database
      - ./var/ssl:/opt/ejabberd/ssl
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
    environment:
      - XMPP_DOMAIN=coldfix.de coldfix.eu fireflake.de fireflake.eu
      - TZ=Europe/Berlin
      - EJABBERD_SKIP_MAKE_SSLCERT=1
    hostname: coldfix.de
    domainname: coldfix.de
    cap_drop:
      - all
